project:
  type: website

website:
  title: "EPPS 3656 - Github Website"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Assignments"
      - text: "Group Project"
      - text: "About"
        href: about.qmd
        
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

