---
title: "Assignment 1"
---

# Question 1

## 1. Amazon:

This is one of the most popular application in the US. It has actively collected and taken advantages of millions of their customers, including me, to advance their revenue. They have analysed my history purchases, and search to manipulate my shopping habit.

The history purchase provide them which products, manufacturers, price range, and categories I preferred to spend money on. Also, the time I usually went window shopping and decided to make payment is exposed to Amazon. According to those information, whenever I log into my Amazon account, the algorithms shows me a list of products, which they believe I will be interested to buy.

## 2. Facebook

Like Amazon, Facebook has collected my footprint on social media since I created an account on their platform. Everything I do on Facebook, from every pages or group I followed to every single thread I interacted via emocons or comments, gives out my personal references. It includes political bias, favorite images, destinations, and so on.

However, unlike Amazon, Facebook usually sell my personal data to marketing firms. Those companies used those data to create a profile matching with all my preference. As a result, they can send out customized advertising campaigns or digital contents which might influence my decisions in their favor.

## 3. Netflix

Netflix has dominated streaming services for ages. Their revenue comes from monthly subscriptions around the world. The more users make commitment to their service every month, the more profit Netflix receive. Accordingly, they have analyzed my watching patterns.

-   What types of movies or shows have I picked? Movies? Documentary series? Reality shows?

-   What languages have I chosen for movies? with or without subtitle?

-   Which category have I preferred? Comedy? Horror? Fantasy?

All of those help them to offer me good recommendation, or plan a reasonable purchase in future. On my end, I might find it satisfied with the Netflix library and continue to pay monthly subscription.

# Question 2

## 1. Public Safety

### Purpose

### Function

### Interface Design
